name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Ubuntu
            os: ubuntu-24.04
            cmake_preset: clang-release

          - name: Windows
            os: windows-latest
            cmake_preset: windows-release

    name: ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Developer Command Prompt
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: |
          curl -L -o ninja-linux.zip https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip
          unzip ninja-linux.zip -d bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install FLTK dependencies
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: sudo apt-get update -y && sudo apt-get install -y libglu1-mesa-dev libwayland-dev wayland-protocols libdbus-1-dev libxkbcommon-dev libegl-dev libopengl-dev libpango1.0-dev libgtk-3-dev

      - name: Configure
        run: cmake --preset ${{ matrix.cmake_preset }}

      - name: Build
        run: cmake --build build